
-- MySQL Script generated by MySQL Workbench
-- czw, 18 paź 2018, 14:54:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema EbookManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EbookManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EbookManager` DEFAULT CHARACTER SET utf8 ;
USE `EbookManager` ;

-- -----------------------------------------------------
-- Table `EbookManager`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`app_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `login` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `role` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `EbookManager`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`authors` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `EbookManager`.`book_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`book_store` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `web` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `EbookManager`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`books` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `bookstore_id` BIGINT(20) NULL DEFAULT NULL,
  `owner_id` BIGINT(20) NULL DEFAULT NULL,
  `in_reader` BIT(1) NULL DEFAULT NULL,
  `is_read` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh3hiyanpb27qcoh0w39n6uu27` (`bookstore_id` ASC),
  INDEX `FKchxxccg57j4rd6fpg7sag18tw` (`owner_id` ASC),
  CONSTRAINT `FKchxxccg57j4rd6fpg7sag18tw`
    FOREIGN KEY (`owner_id`)
    REFERENCES `EbookManager`.`app_user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FKh3hiyanpb27qcoh0w39n6uu27`
    FOREIGN KEY (`bookstore_id`)
    REFERENCES `EbookManager`.`book_store` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `EbookManager`.`books_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`books_authors` (
  `books_id` BIGINT(20) NOT NULL,
  `authors_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`books_id`, `authors_id`),
  INDEX `FK20menrngp9wi9at1dsu5cbb8o` (`authors_id` ASC),
  CONSTRAINT `FK20menrngp9wi9at1dsu5cbb8o`
    FOREIGN KEY (`authors_id`)
    REFERENCES `EbookManager`.`authors` (`id`),
  CONSTRAINT `FKq3f75b7gkvjqe5k1pa5emwpgw`
    FOREIGN KEY (`books_id`)
    REFERENCES `EbookManager`.`books` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `EbookManager`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`genres` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `EbookManager`.`books_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EbookManager`.`books_genres` (
  `book_id` BIGINT(20) NOT NULL,
  `genres_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`book_id`, `genres_id`),
  INDEX `FKd69nnd4vn4ql5pp5i0fmmr7de` (`genres_id` ASC),
  CONSTRAINT `FKd69nnd4vn4ql5pp5i0fmmr7de`
    FOREIGN KEY (`genres_id`)
    REFERENCES `EbookManager`.`genres` (`id`),
  CONSTRAINT `FKlv42b6uemg63q27om39jjbt9o`
    FOREIGN KEY (`book_id`)
    REFERENCES `EbookManager`.`books` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

